version: "3"

x-redis-base: &redis-base
  image: docker.io/bitnami/redis-cluster:7.0.10
  environment:
    ALLOW_EMPTY_PASSWORD: yes
    REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5

services:

  redis-node-0:
    container_name: redis-node-0
    <<: *redis-base
  redis-node-1:
    container_name: redis-node-1
    <<: *redis-base
  redis-node-2:
    container_name: redis-node-2
    <<: *redis-base
  redis-node-3:
    container_name: redis-node-3
    <<: *redis-base
  redis-node-4:
    container_name: redis-node-4
    <<: *redis-base

  redis-node-5:
    container_name: redis-node-5
    <<: *redis-base
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_NODES: redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      REDIS_CLUSTER_REPLICAS: 1
      REDIS_CLUSTER_CREATOR: yes

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - rabbitmq
      - redis-node-1

  # order-db:
  #   image: redis:7.2-bookworm
  #   command: redis-server --requirepass redis --maxmemory 512mb
  
  # redis-2:
  #   image: redis:7.2-bookworm
  #   command: ["redis-server","/etc/redis/redis.conf"]
  #   volumes:
  #     - ./redis/7002/redis.conf:/etc/redis/redis.conf
  #   ports:
  #     - "7002:7002"
  
  # redis-5:
  #   image: redis:7.2-bookworm
  #   command: ["redis-server","/etc/redis/redis.conf"]
  #   volumes:
  #     - ./redis/7005/redis.conf:/etc/redis/redis.conf
  #   ports:
  #     - "7005:7005"


  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - rabbitmq
      - stock-db

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: payment:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - rabbitmq
      - payment-db

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb