version: "3"

x-redis-order-base: &redis-order-base
    image: docker.io/bitnami/redis-cluster:7.2
    env_file:
      - env/order_redis.env

x-redis-stock-base: &redis-stock-base
    image: docker.io/bitnami/redis-cluster:7.2
    env_file:
      - env/stock_redis.env

x-redis-payment-base: &redis-payment-base
    image: docker.io/bitnami/redis-cluster:7.2
    env_file:
      - env/payment_redis.env

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - orchestrator
      - order-service
      - stock-service
      - payment-service


  orchestrator:
    build: ./orchestrator
    image : orchestrator:latest
    command : gunicorn -b 0.0.0.0:8001 -w 2 --timeout 60 --log-level=info app:app
    env_file:
      - env/orchestrator_redis.env
    depends_on:
      - rabbitmq



  order-service:
    build: ./order
    image: order:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 60 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - rabbitmq
      - redis-order-0
      - redis-order-1
      - redis-order-2
      - redis-order-3
      - redis-order-4
      - redis-order-5

  # order-db:
  #   image: redis:7.2-bookworm
  #   command: redis-server --requirepass redis --maxmemory 512mb
  
  redis-order-0:
    <<: *redis-order-base

  redis-order-1:
    <<: *redis-order-base
  
  redis-order-2:
    <<: *redis-order-base
  
  redis-order-3:
    <<: *redis-order-base
  
  redis-order-4:
    <<: *redis-order-base

  redis-order-5:
    <<: *redis-order-base
    ports:
      - 6379:6379
      - 16379:16379
    environment:
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
    depends_on:
      - redis-order-0
      - redis-order-1
      - redis-order-2
      - redis-order-3
      - redis-order-4
    
  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 60 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - rabbitmq
      - redis-stock-0
      - redis-stock-1
      - redis-stock-2
      - redis-stock-3
      - redis-stock-4
      - redis-stock-5

  redis-stock-0:
    <<: *redis-stock-base
    ports:
      - 6380:6380
      - 16380:16380
    environment:
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
    depends_on:
      - redis-stock-1
      - redis-stock-2
      - redis-stock-3
      - redis-stock-4
      - redis-stock-5
  
  redis-stock-1:
    <<: *redis-stock-base
  
  redis-stock-2:
    <<: *redis-stock-base
  
  redis-stock-3:
    <<: *redis-stock-base

  redis-stock-4:
    <<: *redis-stock-base
  
  redis-stock-5:
    <<: *redis-stock-base

  payment-service:
    build: ./payment
    image: payment:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 60 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - rabbitmq
      - redis-payment-0
      - redis-payment-1
      - redis-payment-2
      - redis-payment-3
      - redis-payment-4
      - redis-payment-5

  # payment-db:
  #   image: redis:7.2-bookworm
  #   command: redis-server --requirepass redis --maxmemory 512mb

  redis-payment-0:
    <<: *redis-payment-base
    ports:
      - 6381:6381
      - 16381:16381
    environment:
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'
    depends_on:
      - redis-payment-1
      - redis-payment-2
      - redis-payment-3
      - redis-payment-4
      - redis-payment-5
  
  redis-payment-1:
    <<: *redis-payment-base
  
  redis-payment-2:
    <<: *redis-payment-base
  
  redis-payment-3:
    <<: *redis-payment-base

  redis-payment-4:
    <<: *redis-payment-base
  
  redis-payment-5:
    <<: *redis-payment-base