version: "3"
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - orchestrator
      - order-service
      - stock-service
      - payment-service


  orchestrator:
    build: ./orchestrator
    image : orchestrator:latest
    command : gunicorn -b 0.0.0.0:8001 -w 1 --timeout 30 --log-level=info app:app
    env_file:
      - env/orchestrator_redis.env
    depends_on:
      - rabbitmq
      - orchestrator-db
    deploy:
      resources:
        limits:
          memory: 512M

  orchestrator-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  order-service:
    build: ./order
    image: order:latest
    command: gunicorn -b 0.0.0.0:5000 -w 4 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - rabbitmq
      - order-db
    deploy:
      resources:
        limits:
          memory: 512M


  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 4 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - rabbitmq
      - stock-db
    deploy:
      resources:
        limits:
          memory: 512M

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: payment:latest
    command: gunicorn -b 0.0.0.0:5000 -w 4 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - rabbitmq
      - payment-db
    deploy:
      resources:
        limits:
          memory: 512M

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
